// login-form/src/app/app.component.ts
import { Component, ViewEncapsulation } from '@angular/core';
import { Input } from '@angular/core';
import { Output } from '@angular/core';
import { EventEmitter } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  encapsulation: ViewEncapsulation.Native
})
export class AppComponent {
  @Input() labelEmail = 'Email';
  @Input() labelPassword = 'Password';
  @Output() onSuccess = new EventEmitter()

  login: string = "";
  password: string = "";

  submit() {
    this.onSuccess.emit({login: this.login})
    this.password = "";
    this.login = "";
  }
}

<form (ngSubmit)="submit()" #form="ngForm">
    <div class="input-container">
        <label for="email">{{labelEmail}}</label>
        <input id="email" name="email" type="email" [(ngModel)]="login" required>
    </div>
    <div class="input-container">
        <label for="password">{{labelPassword}}</label>
        <input id="password" name="password" type="password" [(ngModel)]="password" required>
    </div>
    <button class="primary" type="submit" [disabled]="form.form.invalid">Login</button>
</form>

// react-login/src/App.js
import React, { Component } from 'react';
import './App.css';

class App extends Component {
  constructor() {
    super();
    this.disabled = true;
  }
  render() {
    return (
      <form>
        <div className="input-container">
          <label htmlFor="email">Email</label>
          <input id="email" name="email" type="email" required />
        </div>
        <div className="input-container">
          <label htmlFor="password">Mot de passe</label>
          <input id="password" name="password" type="password" required />
        </div>
        <button className="primary" type="submit" disabled={this.disabled}>Login</button>
      </form>
    );
  }
}

export default App;
